# Generated by Django 4.1.7 on 2023-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.IntegerField(max_length=10000, primary_key=True, serialize=False)),
                ('EmployeeEmail', models.EmailField(max_length=254)),
                ('EmployeeFirstName', models.CharField(max_length=20)),
                ('EmployeeLastName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=80)),
                ('EmployeeRole', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Clerk', 'Clerk'), ('Retail', 'Retail')], max_length=20, unique=True)),
            ],
        ),
    ]
