# Generated by Django 4.1.7 on 2023-04-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_produc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Products',
        ),
    ]
