# Generated by Django 4.1.7 on 2023-04-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_products_product_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
