# Generated by Django 4.1.7 on 2023-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
