# Generated by Django 4.1.7 on 2023-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_name_product_title_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeRole',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Clerk', 'Clerk'), ('Retail', 'Retail')], max_length=20),
        ),
    ]
