# Generated by Django 4.1.7 on 2023-04-06 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_employee_employeerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('privilege', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeEmail',
            new_name='employeeEmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeFirstName',
            new_name='employeeFirstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeID',
            new_name='employeeID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeLastName',
            new_name='employeeLastName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeRole',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeePassword',
            field=models.CharField(default='password', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeePhone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sessionID',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeRole_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='accounts.roles'),
            preserve_default=False,
        ),
    ]
